version: '3.4'

services:
  rawsocketsample:
    image: ${DOCKER_REGISTRY-}rawsocketsample
    container_name: rawsocketsample
    build:
      context: .
      dockerfile: RawSocketSample/Dockerfile
    cap_add:
      - SYS_PTRACE

  remoteclient:
    image: ${DOCKER_REGISTRY-}remoteclient

    build:
      context: .
      dockerfile: RemoteClient/Dockerfile